Neural Morphology for Translation Lookup
oscii-lab/lex pull request #21
Opened 2016-09-21 01:59 UTC by papajohn

2016-09-21 02:00 UTC, papajohn commented
See https://github.com/lilt/core/issues/412 for experimental results.

2016-09-27 14:53 UTC, joewue requested changes

2016-09-27 14:53 UTC, joewue commented on src/main/java/org/oscii/Main.java
> +            if (morph.length == langs.length) {
there should be some feedback to the user that parameters don't match.

2016-09-27 14:53 UTC, joewue commented on src/main/java/org/oscii/morph/MorphologyManager.java
> +            return stems.get(0);
Did you also try merging the results from multiple possible stems?

2016-09-27 21:05 UTC, papajohn commented on src/main/java/org/oscii/morph/MorphologyManager.java
> +            return stems.get(0);
Our interface only supports showing the translations of one term at the moment, so a merged set can't be displayed clearly.

2016-09-27 21:20 UTC, papajohn commented on src/main/java/org/oscii/Main.java
> +            if (morph.length == langs.length) {
Fixed

2016-10-04 03:14 UTC, merged